package drrs;

/**
* drrs/drrsCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL/drrs.idl
* Friday, November 17, 2017 12:34:44 PM EST
*/

public final class drrsCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public drrs.drrsCorba value = null;

  public drrsCorbaHolder ()
  {
  }

  public drrsCorbaHolder (drrs.drrsCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = drrs.drrsCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    drrs.drrsCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return drrs.drrsCorbaHelper.type ();
  }

}
