package drrs;


/**
* drrs/drrsCorbaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL/drrs.idl
* Sunday, October 29, 2017 1:29:21 AM EDT
*/

public abstract class drrsCorbaPOA extends org.omg.PortableServer.Servant
 implements drrs.drrsCorbaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createRoom", new java.lang.Integer (0));
    _methods.put ("deleteRoom", new java.lang.Integer (1));
    _methods.put ("bookRoom", new java.lang.Integer (2));
    _methods.put ("getAvailableTimeSlot", new java.lang.Integer (3));
    _methods.put ("cancelBooking", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  /* Admin */
       case 0:  // drrs/drrsCorba/createRoom
       {
         String adminId = in.read_string ();
         int roomNumber = in.read_long ();
         String date = in.read_string ();
         String listOfTimeSlots[] = drrs.LISTTimeSlotHelper.read (in);
         org.omg.CORBA.IntHolder rt = new org.omg.CORBA.IntHolder ();
         this.createRoom (adminId, roomNumber, date, listOfTimeSlots, rt);
         out = $rh.createReply();
         out.write_long (rt.value);
         break;
       }

       case 1:  // drrs/drrsCorba/deleteRoom
       {
         String adminId = in.read_string ();
         int roomNumber = in.read_long ();
         String date = in.read_string ();
         String listOfTimeSlots[] = drrs.LISTTimeSlotHelper.read (in);
         org.omg.CORBA.IntHolder rt = new org.omg.CORBA.IntHolder ();
         this.deleteRoom (adminId, roomNumber, date, listOfTimeSlots, rt);
         out = $rh.createReply();
         out.write_long (rt.value);
         break;
       }


  /* Student */
       case 2:  // drrs/drrsCorba/bookRoom
       {
         String studentId = in.read_string ();
         int roomNumber = in.read_long ();
         String date = in.read_string ();
         String timeSlot = in.read_string ();
         org.omg.CORBA.StringHolder rt = new org.omg.CORBA.StringHolder ();
         this.bookRoom (studentId, roomNumber, date, timeSlot, rt);
         out = $rh.createReply();
         out.write_string (rt.value);
         break;
       }

       case 3:  // drrs/drrsCorba/getAvailableTimeSlot
       {
         String studentId = in.read_string ();
         String date = in.read_string ();
         org.omg.CORBA.StringHolder rt = new org.omg.CORBA.StringHolder ();
         this.getAvailableTimeSlot (studentId, date, rt);
         out = $rh.createReply();
         out.write_string (rt.value);
         break;
       }

       case 4:  // drrs/drrsCorba/cancelBooking
       {
         String studentId = in.read_string ();
         String bookingID = in.read_string ();
         org.omg.CORBA.IntHolder rt = new org.omg.CORBA.IntHolder ();
         this.cancelBooking (studentId, bookingID, rt);
         out = $rh.createReply();
         out.write_long (rt.value);
         break;
       }

       case 5:  // drrs/drrsCorba/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:drrs/drrsCorba:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public drrsCorba _this() 
  {
    return drrsCorbaHelper.narrow(
    super._this_object());
  }

  public drrsCorba _this(org.omg.CORBA.ORB orb) 
  {
    return drrsCorbaHelper.narrow(
    super._this_object(orb));
  }


} // class drrsCorbaPOA
