package drrs;


/**
* drrs/drrsCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL/drrs.idl
* Friday, November 17, 2017 12:34:44 PM EST
*/

public interface drrsCorbaOperations 
{

  /* Admin */
  void createRoom (String adminId, int roomNumber, String date, String[] listOfTimeSlots, org.omg.CORBA.IntHolder rt);
  void deleteRoom (String adminId, int roomNumber, String date, String[] listOfTimeSlots, org.omg.CORBA.IntHolder rt);

  /* Student */
  void bookRoom (String studentId, int roomNumber, String date, String timeSlot, org.omg.CORBA.StringHolder rt, String campusName);
  void getAvailableTimeSlot (String studentId, String date, org.omg.CORBA.StringHolder rt);
  void cancelBooking (String studentId, String bookingID, org.omg.CORBA.IntHolder rt);
  void changeReservation (String studentId, String booking_id, String newCampusName, int newRoomNumber, String newDate, String newTimeSlot, org.omg.CORBA.StringHolder rt);
  void shutdown ();
} // interface drrsCorbaOperations
