package drrs;


/**
* drrs/drrsCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL/drrs.idl
* Sunday, October 29, 2017 11:43:45 PM EDT
*/

public interface drrsCorba extends drrsCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface drrsCorba
