package drrs;


/**
* drrs/drrsCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL/drrs.idl
* Sunday, October 29, 2017 1:29:21 AM EDT
*/

public interface drrsCorbaOperations 
{

  /* Admin */
  void createRoom (String adminId, int roomNumber, String date, String[] listOfTimeSlots, org.omg.CORBA.IntHolder rt);
  void deleteRoom (String adminId, int roomNumber, String date, String[] listOfTimeSlots, org.omg.CORBA.IntHolder rt);

  /* Student */
  void bookRoom (String studentId, int roomNumber, String date, String timeSlot, org.omg.CORBA.StringHolder rt);
  void getAvailableTimeSlot (String studentId, String date, org.omg.CORBA.StringHolder rt);
  void cancelBooking (String studentId, String bookingID, org.omg.CORBA.IntHolder rt);
  void shutdown ();
} // interface drrsCorbaOperations
