package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Hello.idl
* Friday, October 27, 2017 3:58:55 AM EDT
*/

public interface HelloOperations 
{
  String sayHello (String data);
  void shutdown ();
} // interface HelloOperations
