package drrs;


/**
* drrs/drrsCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL/drrs.idl
* Friday, November 17, 2017 12:34:44 PM EST
*/

public interface drrsCorba extends drrsCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface drrsCorba
