package drrs;


/**
* drrs/drrsCorbaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL/drrs.idl
* Friday, November 17, 2017 12:34:44 PM EST
*/

abstract public class drrsCorbaHelper
{
  private static String  _id = "IDL:drrs/drrsCorba:1.0";

  public static void insert (org.omg.CORBA.Any a, drrs.drrsCorba that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static drrs.drrsCorba extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (drrs.drrsCorbaHelper.id (), "drrsCorba");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static drrs.drrsCorba read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_drrsCorbaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, drrs.drrsCorba value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static drrs.drrsCorba narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof drrs.drrsCorba)
      return (drrs.drrsCorba)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      drrs._drrsCorbaStub stub = new drrs._drrsCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static drrs.drrsCorba unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof drrs.drrsCorba)
      return (drrs.drrsCorba)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      drrs._drrsCorbaStub stub = new drrs._drrsCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
