package drrs;


/**
* drrs/LISTTimeSlotHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IDL/drrs.idl
* Friday, November 17, 2017 12:34:44 PM EST
*/

public final class LISTTimeSlotHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public LISTTimeSlotHolder ()
  {
  }

  public LISTTimeSlotHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = drrs.LISTTimeSlotHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    drrs.LISTTimeSlotHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return drrs.LISTTimeSlotHelper.type ();
  }

}
