package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from D:/DD_Project/Workspace/Prac/src/Hello.idl
* Friday, October 27, 2017 3:25:31 AM EDT
*/

public interface HelloOperations 
{
  String sayHello ();
  void shutdown ();
} // interface HelloOperations
